In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
a = [1, 2, 3, 4, 5]
out = np.array(a)
out

array([1, 2, 3, 4, 5])

In [ ]:
print(np.array(a))

[1 2 3 4 5]


In [ ]:
np.array([10, 12, 14, 21, 96])

array([10, 12, 14, 21, 96])

In [ ]:
np.array([True, False])

array([ True, False])

In [ ]:
np.array([True, True * 5,  2])

array([1, 5, 2])

In [ ]:
np.array([True, False, 1, 3, 20.36])

array([ 1.  ,  0.  ,  1.  ,  3.  , 20.36])

In [ ]:
np.array([True, 10, 10, 10+5j])

array([ 1.+0.j, 10.+0.j, 10.+0.j, 10.+5.j])

In [ ]:
np.array([False, 10.36, 12, 4.5J, 'shreyas'])

array(['False', '10.36', '12', '4.5j', 'shreyas'], dtype='<U64')

In [ ]:
np.array([False, 1, 2.3, 5+3j, 'a', {1, 2, 3}])

array([False, 1, 2.3, (5+3j), 'a', {1, 2, 3}], dtype=object)

In [ ]:
np.array([False, 1, 2.3, 5+3j, 'a', {1 : 2, 3 : 4}])

array([False, 1, 2.3, (5+3j), 'a', {1: 2, 3: 4}], dtype=object)

In [ ]:
np.array([False, 1, 2.3, 5+3j, {1, 2, 3}, 'a', {1 : 2, 3 : 4}])

array([False, 1, 2.3, (5+3j), {1, 2, 3}, 'a', {1: 2, 3: 4}], dtype=object)

In [ ]:
a = (1, 45, 63, 52, 631)
np.array(a)

array([  1,  45,  63,  52, 631])

In [ ]:
a = {1, 2, 3, 4, 5}
np.array(a)

array({1, 2, 3, 4, 5}, dtype=object)

In [ ]:
a = {1 : 2, 4 : 8}
np.array(a)

array({1: 2, 4: 8}, dtype=object)

In [ ]:
a = [1, 2, 3, 4, 5]
np.array(a)

array([1, 2, 3, 4, 5])

In [ ]:
np.array([[1, 2, 3],
          [5, 9, 10]])

array([[ 1,  2,  3],
       [ 5,  9, 10]])

In [ ]:
np.array([[1, 2, 3, 4],
          [5, 9, 10, 12]])

array([[ 1,  2,  3,  4],
       [ 5,  9, 10, 12]])

In [ ]:
np.array([[1, 20, 36],
          [40, 45, 13],
          [78, 89, 56]])

array([[ 1, 20, 36],
       [40, 45, 13],
       [78, 89, 56]])

In [ ]:
b = np.array([[1, 20, 36],
          [40, 45, 13],
          [78, 89, 56]])

In [ ]:
np.array([[[1, 2, '3'],
           [4, 5, 6],
           [7, 8, 9]],
          [[10, 11, 12],
           [13, 14, 15],
           [16, 17, 18]],
          [[19, 20, 21],
           [22, 23, 24],
           [25, 26, 27]]])

array([[['1', '2', '3'],
        ['4', '5', '6'],
        ['7', '8', '9']],

       [['10', '11', '12'],
        ['13', '14', '15'],
        ['16', '17', '18']],

       [['19', '20', '21'],
        ['22', '23', '24'],
        ['25', '26', '27']]], dtype='<U21')

In [ ]:
a= np.array([[[1,2,'3'],
           [4,5,6]],
          [[7,8,9],
           [10,11,12]],
          [[13,14,15],
           [16,17,18]],
          [[19,20,21],
           [22,23,24]]])

In [ ]:
a

array([[['1', '2', '3'],
        ['4', '5', '6']],

       [['7', '8', '9'],
        ['10', '11', '12']],

       [['13', '14', '15'],
        ['16', '17', '18']],

       [['19', '20', '21'],
        ['22', '23', '24']]], dtype='<U21')

In [ ]:
a.ndim

3

In [ ]:
b

array([[ 1, 20, 36],
       [40, 45, 13],
       [78, 89, 56]])

In [ ]:
b.ndim

2

In [ ]:
a

array([[['1', '2', '3'],
        ['4', '5', '6']],

       [['7', '8', '9'],
        ['10', '11', '12']],

       [['13', '14', '15'],
        ['16', '17', '18']],

       [['19', '20', '21'],
        ['22', '23', '24']]], dtype='<U21')

In [ ]:
a.dtype

dtype('<U21')

In [ ]:
a

array([[['1', '2', '3'],
        ['4', '5', '6']],

       [['7', '8', '9'],
        ['10', '11', '12']],

       [['13', '14', '15'],
        ['16', '17', '18']],

       [['19', '20', '21'],
        ['22', '23', '24']]], dtype='<U21')

In [ ]:
a.dtype

dtype('<U21')

In [ ]:
a = np.array([1, 23, 34, 56, 90, 145])
a.shape

(6,)

In [ ]:
b = np.array([[1, 20, 36, 45],
          [40, 45, 13, -10],
          [78, 89, 56, 112]])

In [ ]:
b.shape

(3, 4)

In [ ]:
a= np.array([[[1,2,3],
           [4,5,6]],

          [[7,8,9],
           [10,11,12]],

          [[13,14,15],
           [16,17,18]],

          [[19,20,21],
           [22,23,24]]])

In [ ]:
a.shape

(4, 2, 3)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18])
a.ndim

1

In [ ]:
a.reshape(3, 3, 2) # where the product off all element shpould bee equal to the total number of elements in the array

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
a.reshape(6, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
a.reshape(9, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [ ]:
a.reshape(2, 3, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a.reshape(3, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a.reshape(1, 9, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18]]])

In [ ]:
a.reshape(6, 3, 1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]],

       [[13],
        [14],
        [15]],

       [[16],
        [17],
        [18]]])

In [ ]:
b = np.array([[13, 14, 16, 18],
              [15, 17, 102, 230],
              [154, 123, 256, 23],
              [78, 89, 63, 41]])
b.ndim

2

In [ ]:
b.reshape(2, 8, 1)

array([[[ 13],
        [ 14],
        [ 16],
        [ 18],
        [ 15],
        [ 17],
        [102],
        [230]],

       [[154],
        [123],
        [256],
        [ 23],
        [ 78],
        [ 89],
        [ 63],
        [ 41]]])

In [ ]:
b.reshape(4, 4, 1)

array([[[ 13],
        [ 14],
        [ 16],
        [ 18]],

       [[ 15],
        [ 17],
        [102],
        [230]],

       [[154],
        [123],
        [256],
        [ 23]],

       [[ 78],
        [ 89],
        [ 63],
        [ 41]]])

In [ ]:
b.reshape(2, 4, 2)

array([[[ 13,  14],
        [ 16,  18],
        [ 15,  17],
        [102, 230]],

       [[154, 123],
        [256,  23],
        [ 78,  89],
        [ 63,  41]]])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [ ]:
c = a.reshape(3, 2, 3)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [ ]:
c.reshape(9, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18]])

In [ ]:
c.reshape(6, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
c.ndim

3

In [ ]:
d = c.reshape(-1)

In [ ]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [ ]:
np.arange(1, 21, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.arange(1,22,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
np.linspace(10, 20, 5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3, 2, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones(15)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((3, 4, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.identity(5).ndim

2

In [ ]:
a = np.random.randint(1, 101, 20)

In [ ]:
a

array([18, 40, 71, 29, 52, 94, 44, 31, 55, 39,  7, 66, 55, 31, 26, 47, 36,
       84, 40, 58])

In [ ]:
a.reshape(5, 2, 2)

array([[[18, 40],
        [71, 29]],

       [[52, 94],
        [44, 31]],

       [[55, 39],
        [ 7, 66]],

       [[55, 31],
        [26, 47]],

       [[36, 84],
        [40, 58]]])

In [ ]:
np.random.randn(20)

array([ 0.99939921, -0.32415495, -0.82081351, -1.24508423, -2.01866516,
        0.48897976,  0.20618672, -1.27038002, -1.70650338, -1.43378604,
       -1.75518783, -0.7894676 ,  1.46216682,  0.64329462, -1.35980156,
       -1.30418241, -0.80613622,  0.91511565, -0.38241367,  1.62623429])

In [ ]:
np.random.rand(20)

array([0.19597129, 0.74615906, 0.5273526 , 0.59348669, 0.14637345,
       0.50084732, 0.61211122, 0.26741651, 0.64454063, 0.4361626 ,
       0.84917278, 0.53938529, 0.47449883, 0.32191087, 0.24935869,
       0.14676837, 0.75062932, 0.58847004, 0.44276823, 0.67309077])

In [ ]:
a = [1, 2, 3, 4]
b = np.array(a)
b

array([1, 2, 3, 4])

In [ ]:
b

array([1, 2, 3, 4])

In [ ]:
c = b.copy()
c

array([1, 2, 3, 4])

In [ ]:
a[1] = 25
a

[1, 25, 3, 4]

In [ ]:
b

array([1, 2, 3, 4])

In [ ]:
b = np.array(a)
b

array([ 1, 25,  3,  4])

In [ ]:
c

array([1, 2, 3, 4])

In [ ]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [ ]:
arr1 = arr.view()
arr1

array([1, 2, 3, 4])

In [ ]:
arr[0] = 100
arr

array([100,   2,   3,   4])

In [ ]:
arr1

array([100,   2,   3,   4])

In [ ]:
a = np.array([1, 2, 3, 25, 87, 136])
a[3]

np.int64(25)

In [ ]:
a[-3]

np.int64(25)

In [ ]:
a[2]

np.int64(3)

In [ ]:
a = np.array([[40, 50, 70],
              [1, 2, 3],
              [9, 15, 27]])
a[2, 1]

np.int64(15)

In [ ]:
a[1, 2]

np.int64(3)

In [ ]:
a[2, 0]

np.int64(9)

In [ ]:
a[-1, -3]

np.int64(9)

In [ ]:
a = np.arange(1, 13).reshape(4, 3)

In [ ]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a[2, 2]

np.int64(9)

In [ ]:
b = np.arange(1, 25).reshape(3, 2, 4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
b[2, 2, 3]

In [ ]:
np.arange(1, 37, 2).reshape(3, 3, 2)[1, 1, 1]

np.int64(19)

In [ ]:
d = np.arange(1, 37).reshape(3, 3, 4)

In [ ]:
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [ ]:
d[2 , 2, 3]

np.int64(36)

In [ ]:
d[1, 2, 1]

np.int64(22)

In [ ]:
d[2, 1, 3]

np.int64(32)

In [ ]:
a = np.array([[1, 2.3, 5+2j, 6],
              [7, 8, 9, 15]])
a[1, 3]

np.complex128(15+0j)

In [ ]:
a = np.array([[1, 3, 4, 6],
              [7, 89, 20, 15],
              [78, 96, 14, 123]])

a

array([[  1,   3,   4,   6],
       [  7,  89,  20,  15],
       [ 78,  96,  14, 123]])

In [ ]:
a[0:2, 0:3]

array([[ 1,  3,  4],
       [ 7, 89, 20]])

In [ ]:
a[0:3:2, 1:4]

array([[  3,   4,   6],
       [ 96,  14, 123]])

In [ ]:
a[1:3, 1:3]

array([[89, 20],
       [96, 14]])

In [ ]:
a[0:3, 0:3:2]

array([[ 1,  4],
       [ 7, 20],
       [78, 14]])

In [ ]:
a

array([[  1,   3,   4,   6],
       [  7,  89,  20,  15],
       [ 78,  96,  14, 123]])

In [ ]:
a[0:3:2, 0:4:3]

array([[  1,   6],
       [ 78, 123]])

In [ ]:
a = np.array([[1, 3, 4.6, 6],
              [7, 89, 20, 15],
              [78, 96, 14, 123]])

a

array([[  1. ,   3. ,   4.6,   6. ],
       [  7. ,  89. ,  20. ,  15. ],
       [ 78. ,  96. ,  14. , 123. ]])

In [ ]:
a[0:4, 1:4:2]

array([[  3.,   6.],
       [ 89.,  15.],
       [ 96., 123.]])

In [ ]:
a = np.array([[[4, 5, 6, 7], [9, 7, 11, 13]],
              [[14, 16, 18, 20], [17, 125, 362, 25]],
              [[78, 19, 86, 52], [79, 93, 31, 177]]])
a

array([[[  4,   5,   6,   7],
        [  9,   7,  11,  13]],

       [[ 14,  16,  18,  20],
        [ 17, 125, 362,  25]],

       [[ 78,  19,  86,  52],
        [ 79,  93,  31, 177]]])

In [ ]:
a[0:, : , :]

array([[[  4,   5,   6,   7],
        [  9,   7,  11,  13]],

       [[ 14,  16,  18,  20],
        [ 17, 125, 362,  25]],

       [[ 78,  19,  86,  52],
        [ 79,  93,  31, 177]]])

In [ ]:
a[:1, :2, :3]

array([[[ 4,  5,  6],
        [ 9,  7, 11]]])

In [ ]:
a

array([[[  4,   5,   6,   7],
        [  9,   7,  11,  13]],

       [[ 14,  16,  18,  20],
        [ 17, 125, 362,  25]],

       [[ 78,  19,  86,  52],
        [ 79,  93,  31, 177]]])

In [ ]:
a[:, ::, 1::2]

array([[[  5,   7],
        [  7,  13]],

       [[ 16,  20],
        [125,  25]],

       [[ 19,  52],
        [ 93, 177]]])

In [ ]:
a

array([[[  4,   5,   6,   7],
        [  9,   7,  11,  13]],

       [[ 14,  16,  18,  20],
        [ 17, 125, 362,  25]],

       [[ 78,  19,  86,  52],
        [ 79,  93,  31, 177]]])

In [ ]:
a[:1, :, 3:]

array([[[ 7],
        [13]]])

In [ ]:
a[:, :,::3 ]

array([[[  4,   7],
        [  9,  13]],

       [[ 14,  20],
        [ 17,  25]],

       [[ 78,  52],
        [ 79, 177]]])

In [ ]:
a

array([[[  4,   5,   6,   7],
        [  9,   7,  11,  13]],

       [[ 14,  16,  18,  20],
        [ 17, 125, 362,  25]],

       [[ 78,  19,  86,  52],
        [ 79,  93,  31, 177]]])

In [ ]:
a[:1, 1:, ::2]

array([[[ 9, 11]]])

In [ ]:
a[:, 1:, ::2]

array([[[  9,  11]],

       [[ 17, 362]],

       [[ 79,  31]]])

In [ ]:
a[:, :, ::2]

array([[[  4,   6],
        [  9,  11]],

       [[ 14,  18],
        [ 17, 362]],

       [[ 78,  86],
        [ 79,  31]]])

In [ ]:
a

array([[[  4,   5,   6,   7],
        [  9,   7,  11,  13]],

       [[ 14,  16,  18,  20],
        [ 17, 125, 362,  25]],

       [[ 78,  19,  86,  52],
        [ 79,  93,  31, 177]]])

In [ ]:
a[1:, :, ::-1]

array([[[ 20,  18,  16,  14],
        [ 25, 362, 125,  17]],

       [[ 52,  86,  19,  78],
        [177,  31,  93,  79]]])

In [ ]:
a[:, :, ::-1]

array([[[  7,   6,   5,   4],
        [ 13,  11,   7,   9]],

       [[ 20,  18,  16,  14],
        [ 25, 362, 125,  17]],

       [[ 52,  86,  19,  78],
        [177,  31,  93,  79]]])

In [ ]:
a

array([[[  4,   5,   6,   7],
        [  9,   7,  11,  13]],

       [[ 14,  16,  18,  20],
        [ 17, 125, 362,  25]],

       [[ 78,  19,  86,  52],
        [ 79,  93,  31, 177]]])

In [ ]:
a[::-1, ::-1, ::-1]

array([[[177,  31,  93,  79],
        [ 52,  86,  19,  78]],

       [[ 25, 362, 125,  17],
        [ 20,  18,  16,  14]],

       [[ 13,  11,   7,   9],
        [  7,   6,   5,   4]]])

In [ ]:
a

array([[[  4,   5,   6,   7],
        [  9,   7,  11,  13]],

       [[ 14,  16,  18,  20],
        [ 17, 125, 362,  25]],

       [[ 78,  19,  86,  52],
        [ 79,  93,  31, 177]]])

In [ ]:
a[::-1, :, ::-1]

array([[[ 52,  86,  19,  78],
        [177,  31,  93,  79]],

       [[ 20,  18,  16,  14],
        [ 25, 362, 125,  17]],

       [[  7,   6,   5,   4],
        [ 13,  11,   7,   9]]])