In [ ]:
import numpy as np


In [ ]:
np.array([10,20,30,40])

array([10, 20, 30, 40])

In [ ]:
np.array((10,20,30,40))

array([10, 20, 30, 40])

In [ ]:
np.array({10,20,30,40})

array({40, 10, 20, 30}, dtype=object)

In [ ]:
np.array([10,20,30,20.4
          ])

array([10. , 20. , 30. , 20.4])

In [ ]:
np.array([10,20,30,True ])

array([10, 20, 30,  1])

In [ ]:
np.array([10,20,30,20.4
          ,10+5j])

array([10. +0.j, 20. +0.j, 30. +0.j, 20.4+0.j, 10. +5.j])

In [ ]:
np.array([10,20,30,20.4
          ,10+5j,"ANAND"])

array(['10', '20', '30', '20.4', '(10+5j)', 'ANAND'], dtype='<U64')

In [ ]:
np.array([10,20,30,20.4
          ,10+5j])

array([10. +0.j, 20. +0.j, 30. +0.j, 20.4+0.j, 10. +5.j])

In [ ]:
np.array((10,20,30))

array([10, 20, 30])

In [ ]:
np.array({10,20,30})

array({10, 20, 30}, dtype=object)

In [ ]:
np.array({10:[30,20],20:30})

array({10: [30, 20], 20: 30}, dtype=object)

In [ ]:
import numpy as np

In [ ]:
a =[1,2,3,4,5,6]
np.array(a)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.array([[1,4,5,6],
    [34,56,78,78]])

array([[ 1,  4,  5,  6],
       [34, 56, 78, 78]])

In [ ]:
a=np.array([[[1,2,3],
           [4,5,6],
           [7,8,9]],
          [[1,2,3],
           [4,5,6],
           [7,8,9]],
          [[1,2,3],
           [4,5,6],
           [6,7,5]]])

In [ ]:
a=np.array([[[1,2,3],
           [4,5,6],
           [7,8,9]],
          [[1,2,3],
           [4,5,6],
           [7,8,9]],
          [[1,2,3],
           [4,5,6],
           [6,7,5]]])

In [ ]:
a


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [6, 7, 5]]])

In [ ]:
b=np.array([[[1,2,5.0],
             [4,5,6]],
            [[2,3,4],
             [4,5,6]]])

In [ ]:
b


array([[[1., 2., 5.],
        [4., 5., 6.]],

       [[2., 3., 4.],
        [4., 5., 6.]]])

In [ ]:
a.ndim

3

In [ ]:
a.dtype


dtype('int64')

In [ ]:
b.dtype

dtype('float64')

In [ ]:
a


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [6, 7, 5]]])

In [ ]:
a.shape

(3, 3, 3)

In [ ]:
a.shape(2,2)

TypeError: 'tuple' object is not callable

In [ ]:
a1=np.array([1,2,3])

In [ ]:
a1.shape

In [ ]:
b.ndim

In [ ]:
a

In [ ]:
a=np.arange(1,19)

In [ ]:
a


In [ ]:
a.reshape(9,2)

In [ ]:
a.reshape(18)

In [ ]:
a.reshape(3,3,2)

In [ ]:
a.reshape(2,3,3)

In [ ]:
a.reshape(-1)

In [ ]:
np.linspace(1,10,5)

In [ ]:
np.linspace(1,10,2)

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

In [ ]:
arr = np.zeros((2,3,4))
print(arr.shape)

In [ ]:
arr = np.arange(6).reshape(2,3)
print(arr)


In [ ]:
a=np.arange(5)
a.dtype

In [ ]:
arr = np.array([1,2,3], dtype='float32')
print(arr.dtype)

In [ ]:
arr = np.linspace(0,1,5)
print(arr)

In [ ]:
 np.zeros(5)


In [ ]:
np.zeros((2,3))


In [ ]:
np.identity(3)

In [ ]:

arr = np.arange(1,7).reshape(2,3)
print(arr.T.shape)

In [ ]:
arr = np.array([[1,2],[3,4]])
print(arr.shape, arr.ndim)

In [ ]:
p=np.random.randint(50,100,(5,5))

In [ ]:
p.ndim

In [ ]:
arr = np.arange(9).reshape(3,3)
print(arr.ravel())

In [ ]:
np.ones((2,3), dtype=int)